/*
 * Copyright 2022 The graph-support project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.graphper.layout;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Consumer;
import org.graphper.api.Assemble;
import org.graphper.api.Cluster;
import org.graphper.api.FloatLabel;
import org.graphper.api.Graphviz;
import org.graphper.api.Graphviz.GraphvizBuilder;
import org.graphper.api.Line;
import org.graphper.api.Node;
import org.graphper.api.attributes.Layout;
import org.graphper.api.attributes.Rankdir;
import org.graphper.api.attributes.Tend;
import org.graphper.def.FlatPoint;
import org.graphper.draw.DrawGraph;
import org.graphper.draw.LineDrawProp;
import org.graphper.draw.NodeDrawProp;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * A float-label corpus whose placement outcome is dumped in a stable textual form.
 *
 * <p>This exists so that refactors of {@link ExternalLabelPlacer} can be proven outcome-neutral:
 * dump the corpus before the change, dump it after, and diff. The dump is intentionally
 * <em>not</em> checked in as a golden resource, for two reasons. It contains full layout geometry
 * and the layout backends legitimately move nodes, so a baseline would turn every unrelated layout
 * fix into a failure here. And the {@code parallel-pair} cases are not stable <em>across</em>
 * JVMs: which of two indistinguishable parallel edges gets which route depends on unrelated JVM
 * history, and flips for all five layout engines when other test classes happen to run first in
 * the same fork. That flip is upstream of label placement — the routed paths themselves swap — and
 * predates this class.
 *
 * <p>What is asserted permanently is therefore the weaker but stable property that the corpus is
 * reproducible within a JVM. A before/after comparison has to keep the surrounding test set
 * identical between the two dumps.
 *
 * <p>To capture a dump for a before/after comparison:
 * {@code mvn -pl core test -Dtest=ExternalLabelPlacementCorpusTest
 * -Dexternal.label.dump=/tmp/before.txt}
 *
 * <p>Text measurement is pinned by {@link DeterministicMeasureText} in tests, so the numbers do not
 * depend on the host's fonts.
 */
public class ExternalLabelPlacementCorpusTest {

  private static final String DUMP_PROPERTY = "external.label.dump";

  @Test
  public void placementCorpusIsReproducible() {
    String first = dump();
    String second = dump();

    Assertions.assertEquals(first, second, "float label placement is not reproducible");

    String target = System.getProperty(DUMP_PROPERTY);
    if (target != null && !target.isEmpty()) {
      write(Paths.get(target).toAbsolutePath(), first);
    }
  }

  @Test
  public void everyEndpointLabelOfTheCorpusIsPlaced() {
    int placed = 0;
    for (Case entry : corpus()) {
      DrawGraph draw = layout(entry);
      for (Line line : entry.lines) {
        LineDrawProp prop = draw.getLineDrawProp(line);
        if (prop == null) {
          continue;
        }
        Map<FloatLabel, FlatPoint> centers = prop.getFloatLabelFlatCenters();
        for (FloatLabel label : labels(line)) {
          if (label.getTend() == null || prop.getFloatAssemble(label) != null) {
            continue;
          }
          Assertions.assertNotNull(centers.get(label),
                                   entry.name + " lost endpoint label " + label.getLabel());
          placed++;
        }
      }
    }
    Assertions.assertTrue(placed > 0, "corpus contains no endpoint labels");
  }

  // ------------------------------------------------------------------ dump

  private String dump() {
    StringBuilder sb = new StringBuilder();
    sb.append("# Float label placement dump. Generated by ")
        .append(getClass().getSimpleName()).append(".\n");
    for (Case entry : corpus()) {
      DrawGraph draw = layout(entry);
      sb.append("\n===== case: ").append(entry.name).append(" =====\n");
      sb.append("bounds | ").append(num(draw.getMinX())).append(" | ").append(num(draw.getMaxX()))
          .append(" | ").append(num(draw.getMinY())).append(" | ").append(num(draw.getMaxY()))
          .append('\n');
      for (int i = 0; i < entry.lines.size(); i++) {
        Line line = entry.lines.get(i);
        LineDrawProp prop = draw.getLineDrawProp(line);
        if (prop == null) {
          sb.append("line ").append(i).append(" | <absent>\n");
          continue;
        }
        sb.append("line ").append(i)
            .append(" | headStart=").append(prop.isHeadStart())
            .append(" | points=").append(prop.size())
            .append(" | start=").append(point(prop.isEmpty() ? null : prop.get(0)))
            .append(" | end=").append(point(prop.isEmpty() ? null : prop.get(prop.size() - 1)))
            .append('\n');
        for (FloatLabel label : labels(line)) {
          sb.append("  label | tend=").append(label.getTend())
              .append(" | ratio=").append(num(label.getLengthRatio()))
              .append(" | text=").append(label.getLabel() == null ? "-" : label.getLabel())
              .append(" | center=")
              .append(point(prop.getFloatLabelFlatCenters().get(label)));
          Assemble assemble = prop.getFloatAssemble(label);
          if (assemble != null) {
            for (Node cell : assemble.getCells()) {
              NodeDrawProp cellProp = draw.getNodeDrawProp(cell);
              sb.append(" | cell=")
                  .append(cellProp == null ? "-"
                              : num(cellProp.getX()) + "," + num(cellProp.getY()));
            }
          }
          sb.append('\n');
        }
      }
    }
    return sb.toString();
  }

  private DrawGraph layout(Case entry) {
    try {
      return entry.graph.graphAttrs().getLayout().getLayoutEngine().layout(entry.graph);
    } catch (Exception e) {
      throw new IllegalStateException("layout failed for " + entry.name, e);
    }
  }

  private static FloatLabel[] labels(Line line) {
    FloatLabel[] labels = line.lineAttrs().getFloatLabels();
    return labels == null ? new FloatLabel[0] : labels;
  }

  private static String point(FlatPoint point) {
    return point == null ? "-" : num(point.getX()) + "," + num(point.getY());
  }

  private static String num(double d) {
    return String.format(Locale.ROOT, "%.6f", d);
  }

  private static void write(Path target, String content) {
    try {
      if (target.getParent() != null) {
        Files.createDirectories(target.getParent());
      }
      Files.write(target, content.getBytes(StandardCharsets.UTF_8));
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  // ------------------------------------------------------------------ corpus

  /**
   * The corpus. Deliberately mixes cases where the preferred endpoint position is free (single
   * line, sparse fan) with cases where it is contested (parallel edges, wide labels, self loops,
   * clusters, graph labels), so a before/after diff covers both the fast path and the search.
   */
  static List<Case> corpus() {
    List<Case> cases = new ArrayList<>();
    for (Layout layout : Layout.values()) {
      for (Rankdir rankdir : new Rankdir[]{Rankdir.TB, Rankdir.LR}) {
        cases.add(singleLine(layout, rankdir));
        cases.add(parallelPair(layout, rankdir));
        cases.add(fan(layout, rankdir));
        cases.add(chain(layout, rankdir));
      }
    }
    for (Rankdir rankdir : Rankdir.values()) {
      cases.add(wideLabels(rankdir));
      cases.add(mixedFloatLabels(rankdir));
    }
    cases.add(selfLoop());
    cases.add(clustered());
    cases.add(graphLabel());
    cases.add(assembleLabel());
    cases.add(noFloatLabels());
    return cases;
  }

  private static Case singleLine(Layout layout, Rankdir rankdir) {
    Node tail = node("single-tail");
    Node head = node("single-head");
    Line line = endpointLabeled(tail, head, "head", "tail");
    return build("single-line/" + layout + "/" + rankdir, layout, rankdir,
                 b -> b.addLine(line), line);
  }

  private static Case parallelPair(Layout layout, Rankdir rankdir) {
    Node tail = node("pair-tail");
    Node head = node("pair-head");
    Line first = endpointLabeled(tail, head, "first head label", "first tail label");
    Line second = endpointLabeled(tail, head, "second head label", "second tail label");
    return build("parallel-pair/" + layout + "/" + rankdir, layout, rankdir,
                 b -> b.addLine(first).addLine(second), first, second);
  }

  private static Case fan(Layout layout, Rankdir rankdir) {
    Node tail = node("fan-tail");
    List<Line> lines = new ArrayList<>();
    for (int i = 0; i < 5; i++) {
      lines.add(endpointLabeled(tail, node("fan-head-" + i), "h" + i, "t" + i));
    }
    return build("fan/" + layout + "/" + rankdir, layout, rankdir,
                 b -> lines.forEach(b::addLine), lines);
  }

  private static Case chain(Layout layout, Rankdir rankdir) {
    List<Node> nodes = new ArrayList<>();
    for (int i = 0; i < 6; i++) {
      nodes.add(node("chain-" + i));
    }
    List<Line> lines = new ArrayList<>();
    for (int i = 0; i + 1 < nodes.size(); i++) {
      lines.add(endpointLabeled(nodes.get(i), nodes.get(i + 1), "in" + i, "out" + i));
    }
    return build("chain/" + layout + "/" + rankdir, layout, rankdir,
                 b -> lines.forEach(b::addLine), lines);
  }

  private static Case wideLabels(Rankdir rankdir) {
    Node tail = node("wide-tail");
    Node head = node("wide-head");
    Line first = endpointLabeled(tail, head,
                                 "a deliberately very wide head label that will not fit",
                                 "a deliberately very wide tail label that will not fit");
    Line second = endpointLabeled(tail, head,
                                  "another very wide head label competing for the same lane",
                                  "another very wide tail label competing for the same lane");
    return build("wide-labels/" + rankdir, Layout.DOT, rankdir,
                 b -> b.addLine(first).addLine(second), first, second);
  }

  private static Case mixedFloatLabels(Rankdir rankdir) {
    Node tail = node("mixed-tail");
    Node head = node("mixed-head");
    Line line = Line.builder(tail, head)
        .floatLabels(FloatLabel.builder().label("along the edge").lengthRatio(0.5).build(),
                     FloatLabel.builder().label("near the middle").lengthRatio(0.85).build(),
                     FloatLabel.builder().label("head end").tend(Tend.HEAD).build(),
                     FloatLabel.builder().label("tail end").tend(Tend.TAIL)
                         .offset(-2, -2).build())
        .build();
    return build("mixed-float-labels/" + rankdir, Layout.DOT, rankdir,
                 b -> b.addLine(line), line);
  }

  private static Case selfLoop() {
    Node only = node("loop-node");
    Line loop = endpointLabeled(only, only, "loop head", "loop tail");
    Line other = endpointLabeled(only, node("loop-peer"), "peer head", "peer tail");
    return build("self-loop", Layout.DOT, Rankdir.TB,
                 b -> b.addLine(loop).addLine(other), loop, other);
  }

  private static Case clustered() {
    Node a = node("cluster-a");
    Node b = node("cluster-b");
    Node c = node("cluster-c");
    Line inside = endpointLabeled(a, b, "inside head", "inside tail");
    Line crossing = endpointLabeled(b, c, "crossing head", "crossing tail");
    Cluster cluster = Cluster.builder().label("a labelled cluster").addNode(a, b).build();
    return build("clustered", Layout.DOT, Rankdir.TB,
                 g -> g.cluster(cluster).addNode(c).addLine(inside).addLine(crossing),
                 inside, crossing);
  }

  private static Case graphLabel() {
    Node tail = node("graph-label-tail");
    Node head = node("graph-label-head");
    Line line = endpointLabeled(tail, head, "head beside the graph label",
                                "tail beside the graph label");
    return build("graph-label", Layout.DOT, Rankdir.TB,
                 b -> b.label("a graph label that occupies space").addLine(line), line);
  }

  private static Case assembleLabel() {
    Node cell = Node.builder().id("assemble-cell").label("cell").build();
    Assemble assemble = Assemble.builder().width(40).height(20).addCell(0, 0, cell).build();
    Node tail = node("assemble-tail");
    Node head = node("assemble-head");
    Line line = Line.builder(tail, head)
        .floatLabels(FloatLabel.builder().tend(Tend.HEAD).assemble(assemble).build(),
                     FloatLabel.builder().label("plain tail").tend(Tend.TAIL).build())
        .build();
    return build("assemble-label", Layout.DOT, Rankdir.LR, b -> b.addLine(line), line);
  }

  private static Case noFloatLabels() {
    Node tail = node("bare-tail");
    Node head = node("bare-head");
    Line line = Line.builder(tail, head).label("an ordinary edge label").build();
    return build("no-float-labels", Layout.DOT, Rankdir.TB, b -> b.addLine(line), line);
  }

  private static Node node(String id) {
    return Node.builder().id(id).label(id).build();
  }

  private static Line endpointLabeled(Node tail, Node head, String headText, String tailText) {
    return Line.builder(tail, head)
        .floatLabels(FloatLabel.builder().label(headText).tend(Tend.HEAD).build(),
                     FloatLabel.builder().label(tailText).tend(Tend.TAIL).build())
        .build();
  }

  private static Case build(String name, Layout layout, Rankdir rankdir,
                            Consumer<GraphvizBuilder> shape, Line... lines) {
    return build(name, layout, rankdir, shape, Arrays.asList(lines));
  }

  private static Case build(String name, Layout layout, Rankdir rankdir,
                            Consumer<GraphvizBuilder> shape, List<Line> lines) {
    GraphvizBuilder builder = Graphviz.digraph().layout(layout).rankdir(rankdir);
    shape.accept(builder);
    return new Case(name, builder.build(), lines);
  }

  static final class Case {

    final String name;

    final Graphviz graph;

    final List<Line> lines;

    Case(String name, Graphviz graph, List<Line> lines) {
      this.name = name;
      this.graph = graph;
      this.lines = lines;
    }
  }
}
