/*
 * Copyright 2022 The graph-support project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.graphper.layout;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Locale;
import org.graphper.def.FlatPoint;
import org.graphper.layout.Cell.RootCell;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Locks down the full geometry of every {@link RootCell} produced by the frozen record-label
 * grammar.
 *
 * <p>{@link CellLabelCompilerTest} only asserts tree depth, leaf count and port lookup — it says
 * nothing about {@code width} / {@code height} / {@code offset}, which is precisely what the
 * geometry code computes. This test dumps every cell of every corpus entry, across several
 * parameter combinations, and compares the result against a checked-in golden file. The golden file
 * was generated from the implementation that existed before the record refactor, so any drift in
 * the geometry backend shows up as a diff instead of passing silently.
 *
 * <p>Geometry is only reproducible because {@link DeterministicMeasureText} wins the
 * {@code MeasureText} SPI selection in tests; with the AWT implementation the numbers would depend
 * on the host's fonts.
 *
 * <p>To regenerate after an intentional change:
 * {@code mvn -pl core test -Dtest=RecordGeometryGoldenTest -Drecord.golden.regenerate=true}
 */
public class RecordGeometryGoldenTest {

  private static final String GOLDEN_RESOURCE = "/record-geometry-golden.txt";

  private static final String GOLDEN_SOURCE_PATH =
      "src/test/resources/record-geometry-golden.txt";

  /**
   * Parameter combinations, chosen to exercise the plain path, the margin path, the minimum-cell
   * size compensation path ({@code alignMinSize}) and the flipped default orientation.
   */
  private static final Params[] PARAMS = {
      new Params("default", null, 14, null, null, false),
      new Params("flip", null, 14, null, null, true),
      new Params("margin", "Times New Roman", 14, new FlatPoint(8, 16), null, false),
      new Params("minsize", null, 14, null, new FlatPoint(54, 108), false),
      new Params("margin+minsize", null, 20, new FlatPoint(4, 10), new FlatPoint(72, 144), true),
  };

  @Test
  public void geometryMatchesGolden() throws IOException {
    String actual = dumpAll();

    if (Boolean.parseBoolean(System.getProperty("record.golden.regenerate"))) {
      Path target = Paths.get(GOLDEN_SOURCE_PATH).toAbsolutePath();
      Files.write(target, actual.getBytes(StandardCharsets.UTF_8));
      Assertions.fail("Golden file regenerated at " + target
                          + " — re-run without -Drecord.golden.regenerate to verify.");
    }

    String expected = readGolden();
    Assertions.assertEquals(expected, actual,
                            "Record cell geometry drifted from the golden baseline. If the change "
                                + "is intentional, regenerate with "
                                + "-Drecord.golden.regenerate=true and review the diff carefully.");
  }

  private String dumpAll() {
    StringBuilder sb = new StringBuilder();
    sb.append("# Record label geometry golden file. Generated by RecordGeometryGoldenTest.\n");
    sb.append("# Columns: path | id | isHor | width | height | offsetX | offsetY | label\n");

    for (Params params : PARAMS) {
      sb.append("\n===== params: ").append(params.name).append(" =====\n");
      for (String label : RecordLabelCorpus.VALID) {
        sb.append("--- label: ").append(escape(label)).append('\n');
        RootCell root = CellLabelCompiler.compile(label, params.fontName, params.fontSize,
                                                  params.margin, params.minCellSize,
                                                  params.defaultVer);
        dumpCell(sb, root, "0");
      }
    }

    sb.append("\n===== rejected =====\n");
    for (String label : RecordLabelCorpus.INVALID) {
      sb.append("--- label: ").append(escape(label)).append(" -> ");
      try {
        CellLabelCompiler.compile(label);
        sb.append("NO EXCEPTION\n");
      } catch (LabelFormatException e) {
        sb.append("LabelFormatException\n");
      }
    }
    sb.append("--- label: <null> -> ");
    try {
      CellLabelCompiler.compile(null);
      sb.append("NO EXCEPTION\n");
    } catch (LabelFormatException e) {
      sb.append("LabelFormatException\n");
    }

    return sb.toString();
  }

  private void dumpCell(StringBuilder sb, Cell cell, String path) {
    FlatPoint offset = cell.getOffset();
    sb.append(path)
        .append(" | ").append(cell.getId() == null ? "-" : cell.getId())
        .append(" | ").append(cell.isHor())
        .append(" | ").append(num(cell.getWidth()))
        .append(" | ").append(num(cell.getHeight()))
        .append(" | ").append(offset == null ? "-" : num(offset.getX()))
        .append(" | ").append(offset == null ? "-" : num(offset.getY()))
        .append(" | ").append(cell.getLabel() == null ? "-" : escape(cell.getLabel()))
        .append('\n');

    for (int i = 0; i < cell.childrenSize(); i++) {
      dumpCell(sb, cell.getChild(i), path + '.' + i);
    }
  }

  private static String num(double d) {
    return String.format(Locale.ROOT, "%.4f", d);
  }

  private static String escape(String s) {
    if (s == null) {
      return "<null>";
    }
    if (s.isEmpty()) {
      return "<empty>";
    }
    return s.replace("\\", "\\\\")
        .replace(" ", "\\s")
        .replace("\n", "\\n")
        .replace("\t", "\\t");
  }

  private String readGolden() {
    try (InputStream in = getClass().getResourceAsStream(GOLDEN_RESOURCE)) {
      Assertions.assertNotNull(in, "Missing golden resource " + GOLDEN_RESOURCE
          + " — generate it with -Drecord.golden.regenerate=true");
      byte[] buf = new byte[in.available() > 0 ? in.available() : 8192];
      java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
      int n;
      while ((n = in.read(buf)) > 0) {
        out.write(buf, 0, n);
      }
      return new String(out.toByteArray(), StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static final class Params {

    private final String name;
    private final String fontName;
    private final double fontSize;
    private final FlatPoint margin;
    private final FlatPoint minCellSize;
    private final boolean defaultVer;

    private Params(String name, String fontName, double fontSize, FlatPoint margin,
                   FlatPoint minCellSize, boolean defaultVer) {
      this.name = name;
      this.fontName = fontName;
      this.fontSize = fontSize;
      this.margin = margin;
      this.minCellSize = minCellSize;
      this.defaultVer = defaultVer;
    }
  }
}
